import 'dart:math' as math;

import 'package:flutter_test/flutter_test.dart';
import 'package:smartlog2/utils/point_cloud_segmenter.dart';
import 'package:vector_math/vector_math_64.dart';

/// A horizontal cylinder lying along +X, centred at [centre].
///
/// Only the upper arc is generated by default, which is what a sensor
/// standing beside a log on the ground actually sees.
List<Vector3> cylinder({
  required Vector3 centre,
  required double radius,
  required double length,
  double fromAngle = 0,
  double toAngle = math.pi,
  int rings = 60,
  int perRing = 40,
}) {
  final points = <Vector3>[];

  for (var i = 0; i < rings; i++) {
    final x = centre.x - length / 2 + length * i / (rings - 1);

    for (var j = 0; j < perRing; j++) {
      final angle = fromAngle + (toAngle - fromAngle) * j / (perRing - 1);

      points.add(
        Vector3(
          x,
          centre.y + radius * math.sin(angle),
          centre.z + radius * math.cos(angle),
        ),
      );
    }
  }

  return points;
}

/// A flat horizontal sheet at height [y].
List<Vector3> ground({
  double y = 0,
  double extent = 3,
  int steps = 60,
}) {
  final points = <Vector3>[];

  for (var i = 0; i < steps; i++) {
    for (var j = 0; j < steps; j++) {
      points.add(
        Vector3(
          -extent / 2 + extent * i / (steps - 1),
          y,
          -extent / 2 + extent * j / (steps - 1),
        ),
      );
    }
  }

  return points;
}

void main() {
  group('findGroundPlane', () {
    test('finds a flat floor under a log', () {
      final scene = <Vector3>[
        ...ground(),
        ...cylinder(
          centre: Vector3(0, 0.15, 0),
          radius: 0.15,
          length: 2,
        ),
      ];

      final plane = PointCloudSegmenter.findGroundPlane(scene);

      expect(plane, isNotNull);
      expect(plane!.normal.dot(Vector3(0, 1, 0)).abs(), closeTo(1.0, 0.05));
      expect(plane.offset, closeTo(0, 0.05));
    });

    test('refuses to call a wall the ground', () {
      // A vertical plane must never be removed: that is how you delete the
      // log you are standing in front of.
      final wall = <Vector3>[];
      for (var i = 0; i < 60; i++) {
        for (var j = 0; j < 60; j++) {
          wall.add(Vector3(-1.5 + 3 * i / 59, 3 * j / 59, 1.0));
        }
      }

      expect(PointCloudSegmenter.findGroundPlane(wall), isNull);
    });

    test('returns null when there is no dominant plane at all', () {
      final log = cylinder(
        centre: Vector3(0, 0.15, 0),
        radius: 0.15,
        length: 2,
      );

      expect(PointCloudSegmenter.findGroundPlane(log), isNull);
    });
  });

  group('growFromSeed', () {
    test('keeps the tapped log and leaves its neighbour behind', () {
      final tapped = cylinder(
        centre: Vector3(0, 0.15, 0),
        radius: 0.15,
        length: 2,
      );
      final neighbour = cylinder(
        centre: Vector3(0, 0.15, 0.6),
        radius: 0.15,
        length: 2,
      );

      final grown = PointCloudSegmenter.growFromSeed(
        [...tapped, ...neighbour],
        // Tap lands on top of the first log.
        Vector3(0, 0.30, 0),
      );

      expect(grown.length, tapped.length);
      // Nothing from the neighbour, which sits a clear 30cm away.
      expect(grown.every((p) => p.z < 0.3), isTrue);
    });

    test('gives up when the tap is nowhere near any surface', () {
      final log = cylinder(
        centre: Vector3(0, 0.15, 0),
        radius: 0.15,
        length: 2,
      );

      final grown = PointCloudSegmenter.growFromSeed(
        log,
        Vector3(0, 5, 0),
      );

      expect(grown, isEmpty);
    });

    test('crosses a gap no wider than the connection radius', () {
      final left = cylinder(
        centre: Vector3(-0.5, 0.15, 0),
        radius: 0.15,
        length: 0.9,
      );
      final right = cylinder(
        centre: Vector3(0.5, 0.15, 0),
        radius: 0.15,
        length: 0.9,
      );

      // The two halves nearly touch, so a scan of one long log broken by a
      // patch of missing depth must still come back whole.
      final grown = PointCloudSegmenter.growFromSeed(
        [...left, ...right],
        Vector3(-0.5, 0.30, 0),
        connectionRadiusMetres: 0.15,
      );

      expect(grown.length, left.length + right.length);
    });
  });

  group('segment', () {
    test('a log on the ground comes back without the ground', () {
      final log = cylinder(
        centre: Vector3(0, 0.15, 0),
        radius: 0.15,
        length: 2,
      );
      final floor = ground();

      final result = PointCloudSegmenter.segment(
        [...floor, ...log],
        Vector3(0, 0.30, 0),
      );

      expect(result.ground, isNotNull);
      expect(result.isEmpty, isFalse);

      // Every surviving point should be log, i.e. well clear of the floor.
      expect(result.points.every((p) => p.y > 0.03), isTrue);

      // And it should be most of the log, not a fragment of it.
      expect(result.points.length, greaterThan(log.length * 0.6));
    });

    test('picks out one log from a yard of three', () {
      final scene = <Vector3>[
        ...ground(),
        ...cylinder(centre: Vector3(0, 0.15, -0.7), radius: 0.15, length: 2),
        ...cylinder(centre: Vector3(0, 0.15, 0), radius: 0.15, length: 2),
        ...cylinder(centre: Vector3(0, 0.15, 0.7), radius: 0.15, length: 2),
      ];

      final result = PointCloudSegmenter.segment(
        scene,
        Vector3(0, 0.30, 0),
      );

      // Only the middle log, so everything should hug z = 0.
      expect(result.points.every((p) => p.z.abs() < 0.3), isTrue);
      expect(result.rejectedCount, greaterThan(0));
    });

    test('a log raised on a rack is not cut off at its underside', () {
      // The ground is a metre below, so removing it must not touch the log.
      final log = cylinder(
        centre: Vector3(0, 1.0, 0),
        radius: 0.15,
        length: 2,
        toAngle: 2 * math.pi,
      );

      final result = PointCloudSegmenter.segment(
        [...ground(), ...log],
        Vector3(0, 1.15, 0),
      );

      expect(result.points.length, log.length);
    });

    test('an empty cloud segments to nothing rather than throwing', () {
      final result = PointCloudSegmenter.segment(const [], Vector3.zero());

      expect(result.isEmpty, isTrue);
      expect(result.ground, isNull);
    });

    test('a scene that is only ground yields no log', () {
      final result = PointCloudSegmenter.segment(
        ground(),
        Vector3(0, 0, 0),
      );

      expect(result.isEmpty, isTrue);
    });
  });
}
