import 'dart:io';

//import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/sawing_models.dart';
import '../models/stack_model.dart';
import '../utils/timber_volume.dart';

class ReportService {
  static final _dateFormat = DateFormat("MMM d, yyyy 'at' h:mm a");

  /// [company] is the seller's own company, read from their profile. It is
  /// never prompted for: when it is empty the line is simply left off.
  Future<File> generateStackReport({
    required StackModel stack,
    required String company,
    required DateTime generatedAt,
  }) async {
    final pdf = pw.Document();

    // Totalled in the trade's own columns, so the report agrees with the
    // figure the user watched add up on screen.
    final total = StackVolumeTotal.of(
      stack.logs.map((log) => VolumeResult.fromCubicFeet(log.volume)),
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return [
            pw.Center(
              child: pw.Text(
                "SMART LOG - TIMBER REPORT",
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
            pw.SizedBox(height: 20),
            // Only printed when the user has actually set a company on their
            // profile -- an empty "Company: -" line looks like a defect.
            if (company.isNotEmpty) _row("Company", company),
            if (stack.customerName != null)
              _row("Customer", stack.customerName!),
            _row(
              "Report Generated",
              _dateFormat.format(generatedAt),
            ),
            _row(
              "Stack Name",
              stack.name,
            ),
            _row(
              "Stack Created",
              _dateFormat.format(stack.createdAt),
            ),
            _row(
              "Total Logs",
              stack.logs.length.toString(),
            ),
            _row(
              "Total Volume",
              "${total.display}  (${stack.totalVolume.toStringAsFixed(3)} ft³)",
            ),
            if (stack.totalCost > 0)
              _row(
                "Total Cost",
                "Rs. ${stack.totalCost.toStringAsFixed(2)}",
              ),
            if (stack.remarks != null) _row("Remarks", stack.remarks!),
            pw.SizedBox(height: 25),
            pw.Header(
              level: 1,
              text: "Wood Log Details",
            ),
            pw.TableHelper.fromTextArray(
              headers: const [
                "No",
                // Girth, not diameter: it is what was measured and what the
                // buyer can check with their own tape.
                "Girth (in)",
                "Length (ft)",
                "Volume",
                "Cost",
                "Added On",
              ],
              data: stack.logs
                  .asMap()
                  .entries
                  .map(
                    (e) => [
                      (e.key + 1).toString(),
                      TimberVolumeCalculator.girthInchesFromDiameter(
                        e.value.diameter,
                      ).toStringAsFixed(2),
                      e.value.lengthFeet.toStringAsFixed(2),
                      VolumeResult.fromCubicFeet(e.value.volume).bookDisplay,
                      e.value.cost > 0
                          ? "Rs. ${e.value.cost.toStringAsFixed(2)}"
                          : "-",
                      _dateFormat.format(e.value.createdAt),
                    ],
                  )
                  .toList(),
            ),
            pw.SizedBox(height: 30),
            pw.Divider(),
            pw.Center(
              child: pw.Text(
                "Generated by Smart Log",
                style: const pw.TextStyle(
                  fontSize: 12,
                ),
              ),
            ),
          ];
        },
      ),
    );

    final dir = await getApplicationDocumentsDirectory();

    final file = File(
      "${dir.path}/SmartLog_Stack_${stack.id}_Report.pdf",
    );

    await file.writeAsBytes(
      await pdf.save(),
    );

    return file;
  }

  /// A cut sheet the sawyer can work from at the bench.
  ///
  /// Deliberately not a picture of the pattern: what someone standing at a
  /// saw needs is the order of the passes and the setback for each one. The
  /// pattern is on the phone; this is the paper beside the machine.
  Future<File> generateCuttingReport({
    required SawPlan plan,
    File? capturedImage,
  }) async {
    final pdf = pw.Document();

    pw.MemoryImage? image;

    if (capturedImage != null) {
      image = pw.MemoryImage(
        await capturedImage.readAsBytes(),
      );
    }

    final kerfCubicFeet =
        (plan.kerfAreaMm2 * plan.logLengthMm) / (304.8 * 304.8 * 304.8);
    final edgingCubicFeet =
        (plan.edgingAreaMm2 * plan.logLengthMm) / (304.8 * 304.8 * 304.8);

    // Grouped by finished size, because a yard picks stock by size and not
    // by which numbered board it happened to be.
    final sizes = <String, int>{};
    for (final board in plan.boards) {
      final key = "${board.width.round()} x ${board.thickness.round()} mm";
      sizes[key] = (sizes[key] ?? 0) + 1;
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return [
            pw.Center(
              child: pw.Text(
                "SMART LOG - CUT SHEET",
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
            pw.SizedBox(height: 6),
            pw.Center(
              child: pw.Text(
                "${plan.strategy.label} - "
                "${_dateFormat.format(DateTime.now())}",
                style: const pw.TextStyle(fontSize: 12),
              ),
            ),
            pw.SizedBox(height: 20),
            if (image != null)
              pw.Center(
                child: pw.Container(
                  height: 220,
                  child: pw.Image(image),
                ),
              ),
            pw.SizedBox(height: 20),
            pw.Header(level: 1, text: "Summary"),
            _row("Boards", plan.boardCount.toString()),
            _row(
              "Sawn timber",
              "${plan.boardVolumeCubicFeet.toStringAsFixed(3)} cu ft",
            ),
            _row(
              "Log volume",
              "${plan.logVolumeCubicFeet.toStringAsFixed(3)} cu ft",
            ),
            _row("Yield", "${plan.yieldPercent.toStringAsFixed(1)} %"),
            _row("Sawdust", "${kerfCubicFeet.toStringAsFixed(3)} cu ft"),
            _row(
              "Edgings and slabs",
              "${edgingCubicFeet.toStringAsFixed(3)} cu ft",
            ),
            _row("Saw passes", plan.sawPasses.toString()),
            _row(
              "Log length",
              "${(plan.logLengthMm / 304.8).toStringAsFixed(2)} ft",
            ),
            if (plan.pricePerCubicFoot > 0)
              _row(
                "Value at Rs. ${plan.pricePerCubicFoot.toStringAsFixed(0)}"
                    "/cu ft",
                "Rs. ${plan.value.toStringAsFixed(2)}",
              ),
            pw.SizedBox(height: 20),
            pw.Header(level: 1, text: "Boards produced"),
            pw.TableHelper.fromTextArray(
              headers: const ["Finished size", "Quantity", "Length"],
              data: [
                for (final entry in sizes.entries)
                  [
                    entry.key,
                    entry.value.toString(),
                    "${(plan.logLengthMm / 304.8).toStringAsFixed(2)} ft",
                  ],
              ],
            ),
            pw.SizedBox(height: 20),
            pw.Header(level: 1, text: "Cut list"),
            pw.Text(
              "Setbacks are measured from the same reference face, in the "
              "order listed.",
              style: const pw.TextStyle(fontSize: 10),
            ),
            pw.SizedBox(height: 8),
            pw.TableHelper.fromTextArray(
              headers: const ["#", "Pass", "Setback (mm)"],
              data: [
                for (final cut in plan.cuts)
                  [
                    cut.order.toString(),
                    cut.description,
                    cut.setback.toStringAsFixed(1),
                  ],
              ],
            ),
            pw.SizedBox(height: 30),
            pw.Divider(),
            pw.Center(
              child: pw.Text(
                "Generated by Smart Log",
                style: const pw.TextStyle(fontSize: 12),
              ),
            ),
          ];
        },
      ),
    );

    final dir = await getApplicationDocumentsDirectory();

    final file = File("${dir.path}/SmartLog_Cut_Sheet.pdf");

    await file.writeAsBytes(await pdf.save());

    return file;
  }

  pw.Widget _row(
    String title,
    String value,
  ) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(
        bottom: 8,
      ),
      child: pw.Row(
        children: [
          pw.Expanded(
            child: pw.Text(
              title,
              style: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.Text(value),
        ],
      ),
    );
  }

  /// Exports a stack as CSV.
  ///
  /// Written by hand rather than with a package because the whole format is
  /// "join with commas, quote anything containing one" -- and the escaping
  /// below is the part that actually matters: a customer named "Perera, W."
  /// would otherwise shift every column after it by one and quietly corrupt
  /// the volumes in the spreadsheet.
  Future<File> generateStackCsv({
    required StackModel stack,
    required String company,
    required DateTime generatedAt,
  }) async {
    String cell(Object? value) {
      final text = "${value ?? ''}";

      if (!text.contains(RegExp(r'[",\n]'))) return text;

      return '"${text.replaceAll('"', '""')}"';
    }

    String row(List<Object?> values) => values.map(cell).join(",");

    final total = StackVolumeTotal.of(
      stack.logs.map((log) => VolumeResult.fromCubicFeet(log.volume)),
    );

    final lines = <String>[
      row(["Smart Log measurement report"]),
      if (company.trim().isNotEmpty) row(["Company", company]),
      row(["Stack", stack.name]),
      if (stack.customerName != null) row(["Customer", stack.customerName]),
      if (stack.remarks != null) row(["Remarks", stack.remarks]),
      row(["Generated", _dateFormat.format(generatedAt)]),
      row([]),
      row([
        "No",
        "Diameter (in)",
        "Length (ft)",
        "Volume (cu ft)",
        "Cost (Rs.)",
        "Measured by",
        "Recorded",
      ]),
      for (var i = 0; i < stack.logs.length; i++)
        row([
          i + 1,
          stack.logs[i].diameter.toStringAsFixed(2),
          stack.logs[i].lengthFeet.toStringAsFixed(2),
          stack.logs[i].volume.toStringAsFixed(3),
          stack.logs[i].cost.toStringAsFixed(2),
          stack.logs[i].stackId == null ? "single log" : "stack",
          stack.logs[i].createdAt.toIso8601String(),
        ]),
      row([]),
      row(["Logs", stack.logs.length]),
      // Both the decimal figure a spreadsheet can sum and the adi/angal
      // reading the trade actually quotes -- the PDF shows both for the same
      // reason, and a CSV that dropped one would not reconcile against it.
      row(["Total volume (cu ft)", stack.totalVolume.toStringAsFixed(3)]),
      row(["Total volume (trade)", "${total.adi} adi ${total.angal} angal"]),
      row(["Total cost (Rs.)", stack.totalCost.toStringAsFixed(2)]),
    ];

    final dir = await getApplicationDocumentsDirectory();
    final file = File("${dir.path}/SmartLog_Stack_${stack.id}_Report.csv");

    // A BOM, so Excel opens the file as UTF-8 instead of guessing the local
    // codepage and mangling any non-ASCII customer name.
    await file.writeAsString("﻿${lines.join("\r\n")}\r\n");

    return file;
  }

  /// Only meaningful for a PDF. A CSV handed to the PDF layout engine is
  /// not a document it can render, so the caller hides the action instead of
  /// offering something that cannot work.
  Future<void> printReport(File pdfFile) async {
    await Printing.layoutPdf(
      onLayout: (_) async => pdfFile.readAsBytes(),
    );
  }

  /// Shares the file under its own name.
  ///
  /// The name used to be hardcoded to "SmartLog_Report.pdf" whatever was
  /// actually being shared, so an exported CSV arrived claiming to be a PDF
  /// and Excel refused to open it -- the file was correct all along, the
  /// label on it was not.
  Future<void> shareReport(File file) async {
    await Printing.sharePdf(
      bytes: await file.readAsBytes(),
      filename: file.uri.pathSegments.last,
    );
  }
}
