import 'dart:io';

//import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/cutting_models.dart';
import '../models/stack_model.dart';
import '../utils/timber_volume.dart';

class ReportService {
  static final _dateFormat = DateFormat("MMM d, yyyy 'at' h:mm a");

  /// [company] is the seller's own company, read from their profile. It is
  /// never prompted for: when it is empty the line is simply left off.
  Future<File> generateStackReport({
    required StackModel stack,
    required String company,
    required DateTime generatedAt,
  }) async {
    final pdf = pw.Document();

    // Totalled in the trade's own columns, so the report agrees with the
    // figure the user watched add up on screen.
    final total = StackVolumeTotal.of(
      stack.logs.map((log) => VolumeResult.fromCubicFeet(log.volume)),
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return [
            pw.Center(
              child: pw.Text(
                "SMART LOG - TIMBER REPORT",
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
            pw.SizedBox(height: 20),
            // Only printed when the user has actually set a company on their
            // profile -- an empty "Company: -" line looks like a defect.
            if (company.isNotEmpty) _row("Company", company),
            if (stack.customerName != null)
              _row("Customer", stack.customerName!),
            _row(
              "Report Generated",
              _dateFormat.format(generatedAt),
            ),
            _row(
              "Stack Name",
              stack.name,
            ),
            _row(
              "Stack Created",
              _dateFormat.format(stack.createdAt),
            ),
            _row(
              "Total Logs",
              stack.logs.length.toString(),
            ),
            _row(
              "Total Volume",
              "${total.display}  (${stack.totalVolume.toStringAsFixed(3)} ft³)",
            ),
            if (stack.totalCost > 0)
              _row(
                "Total Cost",
                "Rs. ${stack.totalCost.toStringAsFixed(2)}",
              ),
            if (stack.remarks != null) _row("Remarks", stack.remarks!),
            pw.SizedBox(height: 25),
            pw.Header(
              level: 1,
              text: "Wood Log Details",
            ),
            pw.TableHelper.fromTextArray(
              headers: const [
                "No",
                // Girth, not diameter: it is what was measured and what the
                // buyer can check with their own tape.
                "Girth (in)",
                "Length (ft)",
                "Volume",
                "Cost",
                "Added On",
              ],
              data: stack.logs
                  .asMap()
                  .entries
                  .map(
                    (e) => [
                      (e.key + 1).toString(),
                      TimberVolumeCalculator.girthInchesFromDiameter(
                        e.value.diameter,
                      ).toStringAsFixed(2),
                      e.value.lengthFeet.toStringAsFixed(2),
                      VolumeResult.fromCubicFeet(e.value.volume).bookDisplay,
                      e.value.cost > 0
                          ? "Rs. ${e.value.cost.toStringAsFixed(2)}"
                          : "-",
                      _dateFormat.format(e.value.createdAt),
                    ],
                  )
                  .toList(),
            ),
            pw.SizedBox(height: 30),
            pw.Divider(),
            pw.Center(
              child: pw.Text(
                "Generated by Smart Log",
                style: const pw.TextStyle(
                  fontSize: 12,
                ),
              ),
            ),
          ];
        },
      ),
    );

    final dir = await getApplicationDocumentsDirectory();

    final file = File(
      "${dir.path}/SmartLog_Stack_${stack.id}_Report.pdf",
    );

    await file.writeAsBytes(
      await pdf.save(),
    );

    return file;
  }

  Future<File> generateReport({
    required CuttingResult result,
    File? capturedImage,
  }) async {
    final pdf = pw.Document();

    pw.MemoryImage? image;

    if (capturedImage != null) {
      image = pw.MemoryImage(
        await capturedImage.readAsBytes(),
      );
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return [
            pw.Center(
              child: pw.Text(
                "SMARTLOG CUTTING REPORT",
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
            pw.SizedBox(height: 20),
            if (image != null)
              pw.Center(
                child: pw.Container(
                  height: 250,
                  child: pw.Image(image),
                ),
              ),
            pw.SizedBox(height: 20),
            pw.Header(
              level: 1,
              text: "Optimization Summary",
            ),
            _row(
              "Boards Produced",
              result.boardCount.toString(),
            ),
            _row(
              "Utilization",
              "${result.utilization.toStringAsFixed(2)} %",
            ),
            _row(
              "Waste",
              "${result.waste.toStringAsFixed(2)} %",
            ),
            _row(
              "Estimated Profit",
              "Rs. ${result.profit.toStringAsFixed(2)}",
            ),
            _row(
              "Log Area",
              result.logArea.toStringAsFixed(2),
            ),
            _row(
              "Board Area",
              result.boardArea.toStringAsFixed(2),
            ),
            _row(
              "Waste Area",
              result.wasteArea.toStringAsFixed(2),
            ),
            _row(
              "Kerf Loss",
              result.kerfLoss.toStringAsFixed(2),
            ),
            _row(
              "Rotation",
              "${result.angle.toStringAsFixed(0)}°",
            ),
            _row(
              "Offset X",
              result.offsetX.toStringAsFixed(2),
            ),
            _row(
              "Offset Y",
              result.offsetY.toStringAsFixed(2),
            ),
            pw.SizedBox(height: 25),
            pw.Header(
              level: 1,
              text: "Board List",
            ),
            pw.TableHelper.fromTextArray(
              headers: const [
                "No",
                "X",
                "Y",
                "Width",
                "Height",
                "Rotation",
              ],
              data: result.boards
                  .map(
                    (e) => [
                      e.index,
                      e.x.toStringAsFixed(2),
                      e.y.toStringAsFixed(2),
                      e.width.toStringAsFixed(2),
                      e.height.toStringAsFixed(2),
                      "${e.rotation.toStringAsFixed(0)}°",
                    ],
                  )
                  .toList(),
            ),
            pw.SizedBox(height: 30),
            pw.Divider(),
            pw.Center(
              child: pw.Text(
                "Generated by Smart Log",
                style: const pw.TextStyle(
                  fontSize: 12,
                ),
              ),
            ),
          ];
        },
      ),
    );

    final dir = await getApplicationDocumentsDirectory();

    final file = File(
      "${dir.path}/SmartLog_Report.pdf",
    );

    await file.writeAsBytes(
      await pdf.save(),
    );

    return file;
  }

  pw.Widget _row(
    String title,
    String value,
  ) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(
        bottom: 8,
      ),
      child: pw.Row(
        children: [
          pw.Expanded(
            child: pw.Text(
              title,
              style: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.Text(value),
        ],
      ),
    );
  }

  Future<void> printReport(
    File pdfFile,
  ) async {
    await Printing.layoutPdf(
      onLayout: (_) async => pdfFile.readAsBytes(),
    );
  }

  Future<void> shareReport(
    File pdfFile,
  ) async {
    await Printing.sharePdf(
      bytes: await pdfFile.readAsBytes(),
      filename: "SmartLog_Report.pdf",
    );
  }
}
