import 'dart:io';

//import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/cutting_models.dart';

class ReportService {
  Future<File> generateReport({
    required CuttingResult result,
    File? capturedImage,
  }) async {
    final pdf = pw.Document();

    pw.MemoryImage? image;

    if (capturedImage != null) {
      image = pw.MemoryImage(
        await capturedImage.readAsBytes(),
      );
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return [
            pw.Center(
              child: pw.Text(
                "SMARTLOG CUTTING REPORT",
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
            pw.SizedBox(height: 20),
            if (image != null)
              pw.Center(
                child: pw.Container(
                  height: 250,
                  child: pw.Image(image),
                ),
              ),
            pw.SizedBox(height: 20),
            pw.Header(
              level: 1,
              text: "Optimization Summary",
            ),
            _row(
              "Boards Produced",
              result.boardCount.toString(),
            ),
            _row(
              "Utilization",
              "${result.utilization.toStringAsFixed(2)} %",
            ),
            _row(
              "Waste",
              "${result.waste.toStringAsFixed(2)} %",
            ),
            _row(
              "Estimated Profit",
              "Rs. ${result.profit.toStringAsFixed(2)}",
            ),
            _row(
              "Log Area",
              result.logArea.toStringAsFixed(2),
            ),
            _row(
              "Board Area",
              result.boardArea.toStringAsFixed(2),
            ),
            _row(
              "Waste Area",
              result.wasteArea.toStringAsFixed(2),
            ),
            _row(
              "Kerf Loss",
              result.kerfLoss.toStringAsFixed(2),
            ),
            _row(
              "Rotation",
              "${result.angle.toStringAsFixed(0)}°",
            ),
            _row(
              "Offset X",
              result.offsetX.toStringAsFixed(2),
            ),
            _row(
              "Offset Y",
              result.offsetY.toStringAsFixed(2),
            ),
            pw.SizedBox(height: 25),
            pw.Header(
              level: 1,
              text: "Board List",
            ),
            pw.TableHelper.fromTextArray(
              headers: const [
                "No",
                "X",
                "Y",
                "Width",
                "Height",
                "Rotation",
              ],
              data: result.boards
                  .map(
                    (e) => [
                      e.index,
                      e.x.toStringAsFixed(2),
                      e.y.toStringAsFixed(2),
                      e.width.toStringAsFixed(2),
                      e.height.toStringAsFixed(2),
                      "${e.rotation.toStringAsFixed(0)}°",
                    ],
                  )
                  .toList(),
            ),
            pw.SizedBox(height: 30),
            pw.Divider(),
            pw.Center(
              child: pw.Text(
                "Generated by SmartLog",
                style: const pw.TextStyle(
                  fontSize: 12,
                ),
              ),
            ),
          ];
        },
      ),
    );

    final dir = await getApplicationDocumentsDirectory();

    final file = File(
      "${dir.path}/SmartLog_Report.pdf",
    );

    await file.writeAsBytes(
      await pdf.save(),
    );

    return file;
  }

  pw.Widget _row(
    String title,
    String value,
  ) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(
        bottom: 8,
      ),
      child: pw.Row(
        children: [
          pw.Expanded(
            child: pw.Text(
              title,
              style: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.Text(value),
        ],
      ),
    );
  }

  Future<void> printReport(
    File pdfFile,
  ) async {
    await Printing.layoutPdf(
      onLayout: (_) async => pdfFile.readAsBytes(),
    );
  }

  Future<void> shareReport(
    File pdfFile,
  ) async {
    await Printing.sharePdf(
      bytes: await pdfFile.readAsBytes(),
      filename: "SmartLog_Report.pdf",
    );
  }
}
