// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
 //options: DefaultFirebaseOptions.currentPlatform,
//);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAarIgXpx5BdUAgzgSoq4Yo1gUKMT7x7fA',
    appId: '1:426376339171:web:1e62f2ee664afe84242fd6',
    messagingSenderId: '426376339171',
    projectId: 'smart-log-a7a8b',
    authDomain: 'smart-log-a7a8b.firebaseapp.com',
    storageBucket: 'smart-log-a7a8b.firebasestorage.app',
    measurementId: 'G-T9RHE4F2HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVDoBN9v4S6WK8v8SpFPGPEk7XdkhAnSo',
    appId: '1:426376339171:android:1d0d64837f81b849242fd6',
    messagingSenderId: '426376339171',
    projectId: 'smart-log-a7a8b',
    storageBucket: 'smart-log-a7a8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Ws7fnY7LgHR-c-bwtUZCXuzIylqzxVk',
    appId: '1:426376339171:ios:cacb7e01c5b76a4c242fd6',
    messagingSenderId: '426376339171',
    projectId: 'smart-log-a7a8b',
    storageBucket: 'smart-log-a7a8b.firebasestorage.app',
    iosBundleId: 'com.example.smartlog2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Ws7fnY7LgHR-c-bwtUZCXuzIylqzxVk',
    appId: '1:426376339171:ios:cacb7e01c5b76a4c242fd6',
    messagingSenderId: '426376339171',
    projectId: 'smart-log-a7a8b',
    storageBucket: 'smart-log-a7a8b.firebasestorage.app',
    iosBundleId: 'com.example.smartlog2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAarIgXpx5BdUAgzgSoq4Yo1gUKMT7x7fA',
    appId: '1:426376339171:web:ff18aa0716423fc1242fd6',
    messagingSenderId: '426376339171',
    projectId: 'smart-log-a7a8b',
    authDomain: 'smart-log-a7a8b.firebaseapp.com',
    storageBucket: 'smart-log-a7a8b.firebasestorage.app',
    measurementId: 'G-SDCWJVTLEE',
  );
}
